hydra:
  job:
    chdir: true
  run:
    dir: ./result/${name}

data:
    name: "movielens"
    test_size: 0.4
    min_count_rating: 50
    thres_rating: 4
prediction:
    model: "MF"
    k: 5
    n_factors: 150
    lr_all: 0.01
    n_epochs: 20
    reg_all: 0.1
optimization:
    estimator: "DIAG"
    delta: 0.5
    n_candidate: 50
    alpha: 0.2
    gamma_mu: 10
    gamma_sigma: 60
    c_mu: 1
    c_sigma: 0.2
    N: 10
seed: 42
name: default