hydra:
  run:
    dir: ./result/${name}

data:
    name: "movielens"
    test_size: 0.4
prediction:
    model: "USERCF"
    k: 5
    n_factors: 100
    lr_all: 0.01
    n_epochs: 30
    reg_all: 0.02
optimization:
    estimator: "DIAG"
    delta: 0.5
seed: 42
name: default